# Numpy

Numpy is THE library for scientific computing and linear algebra in Python's community and was designed to give users the best of both worlds in programming languages: the speed of `C` language with the readability and elegance of `Python`.

### Why Numpy?
A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example we cannot multiply two lists directly we will have to do it element wise. This is where the role of NumPy comes into play.

In [2]:
import numpy as np

#### Q1: Create a 1D array of numbers from 0 to 9.


In [3]:
vec =np.array(range(10))
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2: Extract all odd numbers from arr.


In [4]:
vec =np.array(range(1,10,2))
vec

array([1, 3, 5, 7, 9])

#### Q3: Replace all odd numbers in arr with -1.


In [5]:
vec = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
vec
vec[vec % 2 == 1 ]=-1
vec

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q4: Convert a 1D array of length 10 to a 2D array with 2 rows


In [6]:
vec
np.reshape(vec,(2,5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

#### Q5: compute the square root for each element in the  array
#### ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [7]:
matrix = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])
matrix
np.power(matrix,2)

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [16, 25, 36]])

#### Q6: compute the exponential for each element in the above array


In [8]:
matrix
np.exp(matrix)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [  7.3890561 ,  20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 , 403.42879349]])

#### Q7: sample 8 elements from uniform dist ([0, 1)


In [9]:
vec_1 = np.random.uniform(0,1,8)
vec_1

array([0.30274905, 0.1069469 , 0.41913847, 0.75865907, 0.77080407,
       0.98002   , 0.68364376, 0.44191072])

#### Q8: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [10]:
np.random.randint(0,10,5)

array([2, 7, 2, 2, 8], dtype=int32)

#### Q9: Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [11]:
vec_2 = np.arange(10,22)
vec_2
matrix_2 = vec_2.reshape(3,4)
matrix_2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

#### Q10: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [29]:
vec_5 = np.arange(5,51,5)
vec_5.reshape(10,1)


array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50]])

#### Q11: Write a NumPy program to create an array of all the even integers from 30 to 70.

In [13]:
vec_3 = np.arange(30,71,2)
vec_3

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### Q12: Write a NumPy program to check whether two arrays are equal (element wise) or not

In [20]:
vec
vec_4 = np.array([ 0, 1,  2, 3,  4, 5,  6, 7,  8, 9])
np.isin(vec,vec_4)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [23]:
# another solution
np.array_equal(vec,vec_4)

False